# Metadata
title: "Melody Starling!"
description: "I’m an interactive web developer, designer, and storyteller. Here's something cool I made!"
keywords: ["web developer", "designer", "jekyll"]
domain: "https://melody.cool"

# Third party services
# (Anything you put here will be public!)
google-analytics:

# Rubygems
# (The ones used for this site breaks GitHub Pages)
plugins:
  - jekyll-auto-image
  - jekyll-postfiles

# Build settings
encoding: utf-8
markdown: kramdown
exclude:
  - .sass-cache/
  - node_modules/
  - .gitignore
  - Gemfile
  - _config.yml
  - glitch.json
  - package.json
  - package-lock.json
  - watch.json
  - "*.save.*"

# Permalinks
permalink: /:name/
